/**
 * GENERATED by scripts/build-farm-market.mjs — do not edit by hand.
 *
 * Aggregated from the 442 farmhouse listings vendored under
 * source-data/99acres-farmhouse-gurgaon/. These are asking prices from one
 * portal on one day, not transacted rates, and every page that renders them
 * says so.
 */

export interface MarketStats {
  listings: number;
  medianPrice: number | null;
  minPrice: number | null;
  maxPrice: number | null;
  medianArea: number | null;
  medianPerSqft: number | null;
  /** [value, count], highest count first. */
  bedrooms: [string, number][];
  facings: [string, number][];
  ownership: [string, number][];
  gated: number;
  corner: number;
  pool: number;
  park: number;
  vaastu: number;
  readyToMove: number;
}

export interface VillageRow extends MarketStats {
  slug: string;
  name: string;
  estates: [string, number][];
  lat: number | null;
  lng: number | null;
}

export interface EstateRow extends MarketStats {
  slug: string;
  name: string;
  villages: [string, number][];
}

/** One acre in square feet — the unit every plot figure here is scaled from. */
export const ACRE_SQFT = 43560;

export const BELT_STATS: MarketStats = {
  "listings": 442,
  "medianPrice": 43100000,
  "minPrice": 7260000,
  "maxPrice": 1170000000,
  "medianArea": 21780,
  "medianPerSqft": 1653,
  "bedrooms": [
    [
      "1",
      175
    ],
    [
      "3",
      95
    ],
    [
      "2",
      86
    ],
    [
      "4",
      40
    ],
    [
      "5",
      35
    ],
    [
      "6",
      9
    ],
    [
      "10",
      2
    ]
  ],
  "facings": [
    [
      "North-East",
      130
    ],
    [
      "East",
      97
    ],
    [
      "North",
      77
    ],
    [
      "West",
      29
    ],
    [
      "North-West",
      28
    ],
    [
      "South",
      13
    ],
    [
      "South-East",
      9
    ],
    [
      "South-West",
      4
    ]
  ],
  "ownership": [
    [
      "Freehold",
      426
    ],
    [
      "Power of Attorney",
      4
    ],
    [
      "Leasehold",
      3
    ],
    [
      "Co-operative Society",
      1
    ]
  ],
  "gated": 304,
  "corner": 248,
  "pool": 0,
  "park": 333,
  "vaastu": 309,
  "readyToMove": 429
};

export const VILLAGES: VillageRow[] = [
  {
    "slug": "sohna",
    "name": "Sohna",
    "listings": 306,
    "medianPrice": 40000000,
    "minPrice": 12000000,
    "maxPrice": 687500000,
    "medianArea": 21780,
    "medianPerSqft": 1572,
    "bedrooms": [
      [
        "1",
        134
      ],
      [
        "3",
        67
      ],
      [
        "2",
        62
      ],
      [
        "4",
        23
      ],
      [
        "5",
        16
      ],
      [
        "6",
        4
      ]
    ],
    "facings": [
      [
        "North-East",
        103
      ],
      [
        "North",
        59
      ],
      [
        "East",
        54
      ],
      [
        "West",
        25
      ],
      [
        "North-West",
        22
      ],
      [
        "South",
        9
      ],
      [
        "South-East",
        7
      ],
      [
        "South-West",
        4
      ]
    ],
    "ownership": [
      [
        "Freehold",
        298
      ],
      [
        "Power of Attorney",
        2
      ]
    ],
    "gated": 224,
    "corner": 188,
    "pool": 0,
    "park": 247,
    "vaastu": 234,
    "readyToMove": 298,
    "estates": [
      [
        "Vatika Westin Sohna Resort",
        258
      ],
      [
        "kisorpure",
        2
      ],
      [
        "DERA ARAVALI GOLDEN HEIGHTS",
        1
      ],
      [
        "Vatika Westin ",
        1
      ],
      [
        "vatika ph 2",
        1
      ]
    ],
    "lat": 28.2376,
    "lng": 77.14941
  },
  {
    "slug": "sohna-road",
    "name": "Sohna Road",
    "listings": 19,
    "medianPrice": 45000000,
    "minPrice": 7260000,
    "maxPrice": 65000000,
    "medianArea": 21780.00000000218,
    "medianPerSqft": 1377,
    "bedrooms": [
      [
        "3",
        6
      ],
      [
        "2",
        6
      ],
      [
        "1",
        5
      ],
      [
        "5",
        2
      ]
    ],
    "facings": [
      [
        "North-East",
        5
      ],
      [
        "North",
        4
      ],
      [
        "West",
        1
      ],
      [
        "South",
        1
      ],
      [
        "East",
        1
      ],
      [
        "North-West",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        19
      ]
    ],
    "gated": 10,
    "corner": 7,
    "pool": 0,
    "park": 11,
    "vaastu": 8,
    "readyToMove": 19,
    "estates": [
      [
        "orchard ",
        1
      ],
      [
        "DLF SPRING field SOHNA ",
        1
      ],
      [
        "Green Orchid Farms",
        1
      ]
    ],
    "lat": 28.4317,
    "lng": 77.03618
  },
  {
    "slug": "manesar",
    "name": "Manesar",
    "listings": 16,
    "medianPrice": 50000000,
    "minPrice": 16500000,
    "maxPrice": 150000000,
    "medianArea": 21780,
    "medianPerSqft": 2306,
    "bedrooms": [
      [
        "3",
        6
      ],
      [
        "2",
        4
      ],
      [
        "1",
        4
      ],
      [
        "6",
        2
      ]
    ],
    "facings": [
      [
        "North-West",
        4
      ],
      [
        "North-East",
        4
      ],
      [
        "East",
        4
      ],
      [
        "West",
        2
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        16
      ]
    ],
    "gated": 11,
    "corner": 6,
    "pool": 0,
    "park": 14,
    "vaastu": 13,
    "readyToMove": 16,
    "estates": [
      [
        "best western country club farms",
        2
      ]
    ],
    "lat": 28.35456,
    "lng": 76.9427
  },
  {
    "slug": "bhondsi",
    "name": "Bhondsi",
    "listings": 11,
    "medianPrice": 101000000,
    "minPrice": 25000000,
    "maxPrice": 1170000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 2066,
    "bedrooms": [
      [
        "1",
        4
      ],
      [
        "3",
        2
      ],
      [
        "2",
        2
      ],
      [
        "6",
        1
      ],
      [
        "5",
        1
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North",
        5
      ],
      [
        "East",
        4
      ]
    ],
    "ownership": [
      [
        "Freehold",
        11
      ]
    ],
    "gated": 8,
    "corner": 7,
    "pool": 0,
    "park": 8,
    "vaastu": 7,
    "readyToMove": 11,
    "estates": [
      [
        "Bhelpa Greens",
        8
      ]
    ],
    "lat": 28.35075,
    "lng": 77.06094
  },
  {
    "slug": "raiseena",
    "name": "Raiseena",
    "listings": 9,
    "medianPrice": 52500000,
    "minPrice": 28000000,
    "maxPrice": 90000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 803,
    "bedrooms": [
      [
        "3",
        3
      ],
      [
        "1",
        2
      ],
      [
        "4",
        2
      ],
      [
        "2",
        1
      ],
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "East",
        4
      ],
      [
        "North-East",
        2
      ],
      [
        "North",
        1
      ],
      [
        "South-East",
        1
      ],
      [
        "South",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        9
      ]
    ],
    "gated": 5,
    "corner": 6,
    "pool": 0,
    "park": 9,
    "vaastu": 9,
    "readyToMove": 8,
    "estates": [
      [
        "Aravali Retreat",
        7
      ]
    ],
    "lat": 28.31551,
    "lng": 77.01957
  },
  {
    "slug": "sector-63a-gurgaon",
    "name": "Sector 63A Gurgaon",
    "listings": 9,
    "medianPrice": 96000000,
    "minPrice": 62500502,
    "maxPrice": 300000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 11111,
    "bedrooms": [
      [
        "5",
        7
      ],
      [
        "4",
        2
      ]
    ],
    "facings": [
      [
        "East",
        8
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        7
      ],
      [
        "Leasehold",
        2
      ]
    ],
    "gated": 9,
    "corner": 9,
    "pool": 0,
    "park": 9,
    "vaastu": 9,
    "readyToMove": 9,
    "estates": [
      [
        "Anant Raj",
        9
      ]
    ],
    "lat": 28.39745,
    "lng": 77.09902
  },
  {
    "slug": "sultanpur",
    "name": "Sultanpur",
    "listings": 5,
    "medianPrice": 27200000,
    "minPrice": 22000000,
    "maxPrice": 37000000,
    "medianArea": 15300.00000000153,
    "medianPerSqft": 1797,
    "bedrooms": [
      [
        "1",
        4
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "East",
        3
      ],
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        5
      ]
    ],
    "gated": 4,
    "corner": 4,
    "pool": 0,
    "park": 2,
    "vaastu": 2,
    "readyToMove": 5,
    "estates": [],
    "lat": 28.47552,
    "lng": 76.85853
  },
  {
    "slug": "garhi-harsaru",
    "name": "Garhi Harsaru",
    "listings": 5,
    "medianPrice": 90000000,
    "minPrice": 30000000,
    "maxPrice": 290000000,
    "medianArea": 21870.000000002186,
    "medianPerSqft": 2066,
    "bedrooms": [
      [
        "1",
        3
      ],
      [
        "4",
        2
      ]
    ],
    "facings": [
      [
        "East",
        3
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        4
      ]
    ],
    "gated": 4,
    "corner": 3,
    "pool": 0,
    "park": 2,
    "vaastu": 2,
    "readyToMove": 5,
    "estates": [],
    "lat": 28.45001,
    "lng": 76.93332
  },
  {
    "slug": "sector-58-gurgaon",
    "name": "Sector 58 Gurgaon",
    "listings": 5,
    "medianPrice": 100000000,
    "minPrice": 51000000,
    "maxPrice": 210000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 2296,
    "bedrooms": [
      [
        "5",
        3
      ],
      [
        "3",
        1
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        2
      ],
      [
        "East",
        2
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        5
      ]
    ],
    "gated": 5,
    "corner": 2,
    "pool": 0,
    "park": 5,
    "vaastu": 5,
    "readyToMove": 5,
    "estates": [
      [
        "Ireo The Grand Arch",
        4
      ],
      [
        "walia bas",
        1
      ]
    ],
    "lat": 28.41288,
    "lng": 77.1122
  },
  {
    "slug": "bandhwari",
    "name": "Bandhwari",
    "listings": 4,
    "medianPrice": 250000000,
    "minPrice": 15000000,
    "maxPrice": 1125000000,
    "medianArea": 87120,
    "medianPerSqft": 3100,
    "bedrooms": [
      [
        "1",
        2
      ],
      [
        "2",
        1
      ],
      [
        "10",
        1
      ]
    ],
    "facings": [
      [
        "East",
        2
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        4
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 1,
    "readyToMove": 4,
    "estates": [],
    "lat": 28.41557,
    "lng": 77.14266
  },
  {
    "slug": "panchgaon",
    "name": "Panchgaon",
    "listings": 3,
    "medianPrice": 60000000,
    "minPrice": 40000000,
    "maxPrice": 60000000,
    "medianArea": 10800,
    "medianPerSqft": 3703,
    "bedrooms": [
      [
        "2",
        1
      ],
      [
        "3",
        1
      ],
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        2
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 2,
    "vaastu": 1,
    "readyToMove": 3,
    "estates": [],
    "lat": 28.31681,
    "lng": 76.89754
  },
  {
    "slug": "badshahpur",
    "name": "Badshahpur",
    "listings": 2,
    "medianPrice": 72500000,
    "minPrice": 45000000,
    "maxPrice": 100000000,
    "medianArea": 65780,
    "medianPerSqft": 1085,
    "bedrooms": [
      [
        "3",
        1
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "South-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ],
      [
        "Leasehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 2,
    "estates": [
      [
        "Ansal Aravalli Retreat Raisina Road",
        1
      ],
      [
        "Ansal retreat Eria Sohna road Badshapur gurgaon",
        1
      ]
    ],
    "lat": 28.39465,
    "lng": 77.04944
  },
  {
    "slug": "sector-95-gurgaon",
    "name": "Sector 95 Gurgaon",
    "listings": 2,
    "medianPrice": 120500000,
    "minPrice": 41000000,
    "maxPrice": 200000000,
    "medianArea": 17000,
    "medianPerSqft": 9014,
    "bedrooms": [
      [
        "2",
        1
      ],
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Power of Attorney",
        1
      ],
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 2,
    "estates": [],
    "lat": 28.41432,
    "lng": 76.90812
  },
  {
    "slug": "hassanpur-tauru",
    "name": "Hassanpur Tauru",
    "listings": 2,
    "medianPrice": 98750000,
    "minPrice": 55000000,
    "maxPrice": 142500000,
    "medianArea": 53010,
    "medianPerSqft": 2273,
    "bedrooms": [
      [
        "2",
        1
      ],
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North-West",
        1
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 1,
    "readyToMove": 2,
    "estates": [],
    "lat": 28.28214,
    "lng": 76.94717
  },
  {
    "slug": "sector-95b-gurgaon",
    "name": "Sector 95B Gurgaon",
    "listings": 2,
    "medianPrice": 22620000,
    "minPrice": 21000000,
    "maxPrice": 24240000,
    "medianArea": 10854,
    "medianPerSqft": 2083,
    "bedrooms": [
      [
        "1",
        2
      ]
    ],
    "facings": [
      [
        "East",
        2
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 2,
    "estates": [
      [
        "Raheja Riyasat Hills",
        1
      ]
    ],
    "lat": 28.43972,
    "lng": 76.9175
  },
  {
    "slug": "bilaspur",
    "name": "Bilaspur",
    "listings": 2,
    "medianPrice": 109500000,
    "minPrice": 99000000,
    "maxPrice": 120000000,
    "medianArea": 21786,
    "medianPerSqft": 24125,
    "bedrooms": [
      [
        "4",
        1
      ],
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ],
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 2,
    "corner": 0,
    "pool": 0,
    "park": 2,
    "vaastu": 2,
    "readyToMove": 2,
    "estates": [
      [
        "Vatika Westin Farms Sohna ",
        1
      ]
    ],
    "lat": 28.28961,
    "lng": 76.86489
  },
  {
    "slug": "teekli",
    "name": "Teekli",
    "listings": 2,
    "medianPrice": 105000000,
    "minPrice": 60000000,
    "maxPrice": 150000000,
    "medianArea": 43560,
    "medianPerSqft": 2410,
    "bedrooms": [
      [
        "1",
        1
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "West",
        1
      ],
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 2,
    "estates": [],
    "lat": 28.4595,
    "lng": 77.02984
  },
  {
    "slug": "garat-pur-bas",
    "name": "Garat Pur Bas",
    "listings": 2,
    "medianPrice": 85500000,
    "minPrice": 36000000,
    "maxPrice": 135000000,
    "medianArea": 43560,
    "medianPerSqft": 1963,
    "bedrooms": [
      [
        "1",
        2
      ]
    ],
    "facings": [
      [
        "North",
        1
      ],
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 2,
    "vaastu": 0,
    "readyToMove": 2,
    "estates": [],
    "lat": 28.33671,
    "lng": 77.01174
  },
  {
    "slug": "iqbalpur",
    "name": "Iqbalpur",
    "listings": 1,
    "medianPrice": 20000000,
    "minPrice": 20000000,
    "maxPrice": 20000000,
    "medianArea": 10250,
    "medianPerSqft": 1951,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.49472,
    "lng": 76.88903
  },
  {
    "slug": "sector-35-gurgaon",
    "name": "Sector 35 Gurgaon",
    "listings": 1,
    "medianPrice": 13125000,
    "minPrice": 13125000,
    "maxPrice": 13125000,
    "medianArea": 7875.000000000788,
    "medianPerSqft": 1667,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 0,
    "estates": [
      [
        "The Nature Valley",
        1
      ]
    ],
    "lat": 28.28482,
    "lng": 77.06603
  },
  {
    "slug": "imt-sohna",
    "name": "IMT Sohna",
    "listings": 1,
    "medianPrice": 16000000,
    "minPrice": 16000000,
    "maxPrice": 16000000,
    "medianArea": 7200,
    "medianPerSqft": 2222,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 0,
    "estates": [],
    "lat": 28.1942,
    "lng": 77.06714
  },
  {
    "slug": "baliawas",
    "name": "Baliawas",
    "listings": 1,
    "medianPrice": 110000000,
    "minPrice": 110000000,
    "maxPrice": 110000000,
    "medianArea": 87120.00000000121,
    "medianPerSqft": 1263,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.42783,
    "lng": 77.1358
  },
  {
    "slug": "aklimpur",
    "name": "Aklimpur",
    "listings": 1,
    "medianPrice": 350000000,
    "minPrice": 350000000,
    "maxPrice": 350000000,
    "medianArea": 88470.00000000885,
    "medianPerSqft": 3956,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [
      [
        "FARM HOUSE",
        1
      ]
    ],
    "lat": 28.36192,
    "lng": 77.03881
  },
  {
    "slug": "sector-8-imt-manesar",
    "name": "Sector 8 IMT Manesar",
    "listings": 1,
    "medianPrice": 85000000,
    "minPrice": 85000000,
    "maxPrice": 85000000,
    "medianArea": 50094.00000000069,
    "medianPerSqft": 1697,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.37413,
    "lng": 76.89624
  },
  {
    "slug": "gurgaon-faridabad-road",
    "name": "Gurgaon Faridabad Road",
    "listings": 1,
    "medianPrice": 750000000,
    "minPrice": 750000000,
    "maxPrice": 750000000,
    "medianArea": 130680.00000000182,
    "medianPerSqft": 5739,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.40806,
    "lng": 77.19445
  },
  {
    "slug": "abhepur",
    "name": "Abhepur",
    "listings": 1,
    "medianPrice": 150000000,
    "minPrice": 150000000,
    "maxPrice": 150000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 3444,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.29404,
    "lng": 77.11544
  },
  {
    "slug": "budhera",
    "name": "Budhera",
    "listings": 1,
    "medianPrice": 27456000,
    "minPrice": 27456000,
    "maxPrice": 27456000,
    "medianArea": 11232.000000001122,
    "medianPerSqft": 2444,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 0,
    "estates": [],
    "lat": 28.48717,
    "lng": 76.93498
  },
  {
    "slug": "gwal-pahari",
    "name": "Gwal Pahari",
    "listings": 1,
    "medianPrice": 175000000,
    "minPrice": 175000000,
    "maxPrice": 175000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 16204,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.43501,
    "lng": 77.14492
  },
  {
    "slug": "bhadashpur-tethar",
    "name": "Bhadashpur Tethar",
    "listings": 1,
    "medianPrice": 50000000,
    "minPrice": 50000000,
    "maxPrice": 50000000,
    "medianArea": 13500.00000000135,
    "medianPerSqft": 3704,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.2772,
    "lng": 77.2026
  },
  {
    "slug": "nimot",
    "name": "Nimot",
    "listings": 1,
    "medianPrice": 55000000,
    "minPrice": 55000000,
    "maxPrice": 55000000,
    "medianArea": 30600.00000000306,
    "medianPerSqft": 1797,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.27482,
    "lng": 77.1534
  },
  {
    "slug": "best-western-country-farms",
    "name": "best western country farms",
    "listings": 1,
    "medianPrice": 21600000,
    "minPrice": 21600000,
    "maxPrice": 21600000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 2000,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.4595,
    "lng": 77.02664
  },
  {
    "slug": "mg-road",
    "name": "MG Road",
    "listings": 1,
    "medianPrice": 270000000,
    "minPrice": 270000000,
    "maxPrice": 270000000,
    "medianArea": 1200,
    "medianPerSqft": 22500,
    "bedrooms": [
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.47957,
    "lng": 77.07999
  },
  {
    "slug": "sector-42-gurgaon",
    "name": "Sector 42 Gurgaon",
    "listings": 1,
    "medianPrice": 110000000,
    "minPrice": 110000000,
    "maxPrice": 110000000,
    "medianArea": 87120.00000000121,
    "medianPerSqft": 1263,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Power of Attorney",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [
      [
        "DLF The Camellias",
        1
      ]
    ],
    "lat": 28.45132,
    "lng": 77.10066
  },
  {
    "slug": "chandu",
    "name": "Chandu",
    "listings": 1,
    "medianPrice": 115000000,
    "minPrice": 115000000,
    "maxPrice": 115000000,
    "medianArea": 54000.0000000054,
    "medianPerSqft": 2130,
    "bedrooms": [
      [
        "6",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.4702,
    "lng": 76.91965
  },
  {
    "slug": "near-delhi-mumbai-expressway-exit",
    "name": "Near Delhi Mumbai Expressway Exit",
    "listings": 1,
    "medianPrice": 23000000,
    "minPrice": 23000000,
    "maxPrice": 23000000,
    "medianArea": 10350.000000001035,
    "medianPerSqft": 2222,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [
      [
        "Sohna",
        1
      ]
    ],
    "lat": 28.4595,
    "lng": 77.02664
  },
  {
    "slug": "kadarpur",
    "name": "Kadarpur",
    "listings": 1,
    "medianPrice": 36000000,
    "minPrice": 36000000,
    "maxPrice": 36000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 3333,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [
      [
        "Bedarwal Consortium Sixty Three Golf Drive",
        1
      ]
    ],
    "lat": 28.39356,
    "lng": 77.09684
  },
  {
    "slug": "jakhopur",
    "name": "Jakhopur",
    "listings": 1,
    "medianPrice": 70000000,
    "minPrice": 70000000,
    "maxPrice": 70000000,
    "medianArea": 65339.90362364216,
    "medianPerSqft": 1071,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.23107,
    "lng": 77.07514
  },
  {
    "slug": "golf-course-ext-road",
    "name": "Golf Course Ext Road",
    "listings": 1,
    "medianPrice": 65000000,
    "minPrice": 65000000,
    "maxPrice": 65000000,
    "medianArea": 21780,
    "medianPerSqft": 2984,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.40333,
    "lng": 77.05053
  },
  {
    "slug": "pachgaon",
    "name": "Pachgaon",
    "listings": 1,
    "medianPrice": 22000000,
    "minPrice": 22000000,
    "maxPrice": 22000000,
    "medianArea": 450.00004500000455,
    "medianPerSqft": 48889,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [
      [
        "country club pachgoan",
        1
      ]
    ],
    "lat": 28.15003,
    "lng": 76.71812
  },
  {
    "slug": "sector-36-sohna",
    "name": "Sector 36 Sohna",
    "listings": 1,
    "medianPrice": 22500000,
    "minPrice": 22500000,
    "maxPrice": 22500000,
    "medianArea": 11691.00000000117,
    "medianPerSqft": 1925,
    "bedrooms": [
      [
        "5",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.288,
    "lng": 77.0646
  },
  {
    "slug": "sector-88b-gurgaon",
    "name": "Sector 88B Gurgaon",
    "listings": 1,
    "medianPrice": 190000000,
    "minPrice": 190000000,
    "maxPrice": 190000000,
    "medianArea": 929.03,
    "medianPerSqft": 19000,
    "bedrooms": [
      [
        "6",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 0,
    "estates": [],
    "lat": 28.44396,
    "lng": 76.95416
  },
  {
    "slug": "hayatpur",
    "name": "Hayatpur",
    "listings": 1,
    "medianPrice": 20000000,
    "minPrice": 20000000,
    "maxPrice": 20000000,
    "medianArea": 21600.00000000216,
    "medianPerSqft": 926,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.41702,
    "lng": 76.93546
  },
  {
    "slug": "sector-67-gurgaon",
    "name": "Sector 67 Gurgaon",
    "listings": 1,
    "medianPrice": 45000000,
    "minPrice": 45000000,
    "maxPrice": 45000000,
    "medianArea": 43560,
    "medianPerSqft": 1033,
    "bedrooms": [
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [
      [
        "M3M Merlin",
        1
      ]
    ],
    "lat": 28.38968,
    "lng": 77.05935
  },
  {
    "slug": "pataudi-road",
    "name": "Pataudi Road",
    "listings": 1,
    "medianPrice": null,
    "minPrice": null,
    "maxPrice": null,
    "medianArea": 3690,
    "medianPerSqft": null,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.43852,
    "lng": 76.97586
  },
  {
    "slug": "sector-77-gurgaon",
    "name": "Sector 77 Gurgaon",
    "listings": 1,
    "medianPrice": 39000000,
    "minPrice": 39000000,
    "maxPrice": 39000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 3611,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "South",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [
      [
        "DLF Privana South",
        1
      ]
    ],
    "lat": 28.37964,
    "lng": 76.99161
  },
  {
    "slug": "tikli",
    "name": "Tikli",
    "listings": 1,
    "medianPrice": 36300000,
    "minPrice": 36300000,
    "maxPrice": 36300000,
    "medianArea": 10890.00000000109,
    "medianPerSqft": 3333,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.35846,
    "lng": 77.02766
  },
  {
    "slug": "sector-5-sohna",
    "name": "Sector-5 Sohna",
    "listings": 1,
    "medianPrice": 45000000,
    "minPrice": 45000000,
    "maxPrice": 45000000,
    "medianArea": 43560,
    "medianPerSqft": 1033,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [
      [
        "Vatika Westin Sohna Resort",
        1
      ]
    ],
    "lat": 28.2376,
    "lng": 77.14941
  },
  {
    "slug": "khalilpur",
    "name": "Khalilpur",
    "listings": 1,
    "medianPrice": 50000000,
    "minPrice": 50000000,
    "maxPrice": 50000000,
    "medianArea": 27225,
    "medianPerSqft": 1837,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.29382,
    "lng": 76.69963
  },
  {
    "slug": "naurangpur",
    "name": "Naurangpur",
    "listings": 1,
    "medianPrice": 85000000,
    "minPrice": 85000000,
    "maxPrice": 85000000,
    "medianArea": 29700.00000000297,
    "medianPerSqft": 2862,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.35437,
    "lng": 76.96833
  },
  {
    "slug": "rithoj",
    "name": "Rithoj",
    "listings": 1,
    "medianPrice": 42750000,
    "minPrice": 42750000,
    "maxPrice": 42750000,
    "medianArea": 12825.000000001282,
    "medianPerSqft": 3333,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.35501,
    "lng": 77.09845
  },
  {
    "slug": "block-c-sheetla-colony",
    "name": "Block C Sheetla Colony",
    "listings": 1,
    "medianPrice": 60000000,
    "minPrice": 60000000,
    "maxPrice": 60000000,
    "medianArea": 535435,
    "medianPerSqft": 112,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Co-operative Society",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.48408,
    "lng": 77.03351
  },
  {
    "slug": "sector-62-gurgaon",
    "name": "Sector 62 Gurgaon",
    "listings": 1,
    "medianPrice": 100000000,
    "minPrice": 100000000,
    "maxPrice": 100000000,
    "medianArea": 1001880.000000014,
    "medianPerSqft": 100,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "estates": [
      [
        "power of attorney",
        1
      ]
    ],
    "lat": 28.40678,
    "lng": 77.08235
  },
  {
    "slug": "block-a-south-city-2",
    "name": "Block A South City 2",
    "listings": 1,
    "medianPrice": 25000000,
    "minPrice": 25000000,
    "maxPrice": 25000000,
    "medianArea": 136125,
    "medianPerSqft": 184,
    "bedrooms": [
      [
        "10",
        1
      ]
    ],
    "facings": [
      [
        "South",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.41829,
    "lng": 77.04528
  },
  {
    "slug": "dhankot",
    "name": "Dhankot",
    "listings": 1,
    "medianPrice": 37000000,
    "minPrice": 37000000,
    "maxPrice": 37000000,
    "medianArea": 10890.00000000109,
    "medianPerSqft": 3398,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 1,
    "readyToMove": 1,
    "estates": [],
    "lat": 28.473,
    "lng": 76.95771
  }
];

export const ESTATES: EstateRow[] = [
  {
    "slug": "vatika-westin-sohna-resort",
    "name": "Vatika Westin Sohna Resort",
    "listings": 259,
    "medianPrice": 40000000,
    "minPrice": 13000000,
    "maxPrice": 160000000,
    "medianArea": 21780.00000000218,
    "medianPerSqft": 1606,
    "bedrooms": [
      [
        "1",
        105
      ],
      [
        "3",
        62
      ],
      [
        "2",
        56
      ],
      [
        "4",
        19
      ],
      [
        "5",
        13
      ],
      [
        "6",
        4
      ]
    ],
    "facings": [
      [
        "North-East",
        93
      ],
      [
        "North",
        52
      ],
      [
        "East",
        46
      ],
      [
        "West",
        20
      ],
      [
        "North-West",
        19
      ],
      [
        "South",
        7
      ],
      [
        "South-East",
        7
      ],
      [
        "South-West",
        4
      ]
    ],
    "ownership": [
      [
        "Freehold",
        253
      ],
      [
        "Power of Attorney",
        1
      ]
    ],
    "gated": 201,
    "corner": 169,
    "pool": 0,
    "park": 216,
    "vaastu": 214,
    "readyToMove": 255,
    "villages": [
      [
        "Sohna",
        258
      ],
      [
        "Sector-5 Sohna",
        1
      ]
    ]
  },
  {
    "slug": "anant-raj",
    "name": "Anant Raj",
    "listings": 9,
    "medianPrice": 96000000,
    "minPrice": 62500502,
    "maxPrice": 300000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 11111,
    "bedrooms": [
      [
        "5",
        7
      ],
      [
        "4",
        2
      ]
    ],
    "facings": [
      [
        "East",
        8
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        7
      ],
      [
        "Leasehold",
        2
      ]
    ],
    "gated": 9,
    "corner": 9,
    "pool": 0,
    "park": 9,
    "vaastu": 9,
    "readyToMove": 9,
    "villages": [
      [
        "Sector 63A Gurgaon",
        9
      ]
    ]
  },
  {
    "slug": "bhelpa-greens",
    "name": "Bhelpa Greens",
    "listings": 8,
    "medianPrice": 110500000,
    "minPrice": 45000000,
    "maxPrice": 1170000000,
    "medianArea": 54450,
    "medianPerSqft": 2066,
    "bedrooms": [
      [
        "1",
        3
      ],
      [
        "6",
        1
      ],
      [
        "5",
        1
      ],
      [
        "2",
        1
      ],
      [
        "3",
        1
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North",
        4
      ],
      [
        "East",
        3
      ]
    ],
    "ownership": [
      [
        "Freehold",
        8
      ]
    ],
    "gated": 6,
    "corner": 6,
    "pool": 0,
    "park": 7,
    "vaastu": 6,
    "readyToMove": 8,
    "villages": [
      [
        "Bhondsi",
        8
      ]
    ]
  },
  {
    "slug": "aravali-retreat",
    "name": "Aravali Retreat",
    "listings": 7,
    "medianPrice": 55000000,
    "minPrice": 28000000,
    "maxPrice": 90000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 803,
    "bedrooms": [
      [
        "1",
        2
      ],
      [
        "3",
        2
      ],
      [
        "2",
        1
      ],
      [
        "5",
        1
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "East",
        4
      ],
      [
        "North-East",
        2
      ],
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        7
      ]
    ],
    "gated": 4,
    "corner": 5,
    "pool": 0,
    "park": 7,
    "vaastu": 7,
    "readyToMove": 7,
    "villages": [
      [
        "Raiseena",
        7
      ]
    ]
  },
  {
    "slug": "ireo-the-grand-arch",
    "name": "Ireo The Grand Arch",
    "listings": 4,
    "medianPrice": 85000000,
    "minPrice": 51000000,
    "maxPrice": 210000000,
    "medianArea": 43560,
    "medianPerSqft": 2009,
    "bedrooms": [
      [
        "5",
        3
      ],
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        2
      ],
      [
        "East",
        2
      ]
    ],
    "ownership": [
      [
        "Freehold",
        4
      ]
    ],
    "gated": 4,
    "corner": 1,
    "pool": 0,
    "park": 4,
    "vaastu": 4,
    "readyToMove": 4,
    "villages": [
      [
        "Sector 58 Gurgaon",
        4
      ]
    ]
  },
  {
    "slug": "kisorpure",
    "name": "kisorpure",
    "listings": 2,
    "medianPrice": 26000000,
    "minPrice": 12000000,
    "maxPrice": 40000000,
    "medianArea": 27225,
    "medianPerSqft": 1010,
    "bedrooms": [
      [
        "1",
        2
      ]
    ],
    "facings": [
      [
        "North-East",
        2
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 2,
    "corner": 2,
    "pool": 0,
    "park": 2,
    "vaastu": 1,
    "readyToMove": 2,
    "villages": [
      [
        "Sohna",
        2
      ]
    ]
  },
  {
    "slug": "best-western-country-club-farms",
    "name": "best western country club farms",
    "listings": 2,
    "medianPrice": 46000000,
    "minPrice": 29500000,
    "maxPrice": 62500000,
    "medianArea": 16290,
    "medianPerSqft": 29201,
    "bedrooms": [
      [
        "3",
        1
      ],
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "East",
        2
      ]
    ],
    "ownership": [
      [
        "Freehold",
        2
      ]
    ],
    "gated": 2,
    "corner": 0,
    "pool": 0,
    "park": 2,
    "vaastu": 2,
    "readyToMove": 2,
    "villages": [
      [
        "Manesar",
        2
      ]
    ]
  },
  {
    "slug": "dera-aravali-golden-heights",
    "name": "DERA ARAVALI GOLDEN HEIGHTS",
    "listings": 1,
    "medianPrice": 100000000,
    "minPrice": 100000000,
    "maxPrice": 100000000,
    "medianArea": 174240.00000000242,
    "medianPerSqft": 574,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Power of Attorney",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "ansal-aravalli-retreat-raisina-road",
    "name": "Ansal Aravalli Retreat Raisina Road",
    "listings": 1,
    "medianPrice": 100000000,
    "minPrice": 100000000,
    "maxPrice": 100000000,
    "medianArea": 88000,
    "medianPerSqft": 1136,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Badshahpur",
        1
      ]
    ]
  },
  {
    "slug": "vatika-westin",
    "name": "Vatika Westin",
    "listings": 1,
    "medianPrice": 30000000,
    "minPrice": 30000000,
    "maxPrice": 30000000,
    "medianArea": 10890.00000000109,
    "medianPerSqft": 2755,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "vatika-ph-2",
    "name": "vatika ph 2",
    "listings": 1,
    "medianPrice": 55000000,
    "minPrice": 55000000,
    "maxPrice": 55000000,
    "medianArea": 27324,
    "medianPerSqft": 2012,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "orchard",
    "name": "orchard",
    "listings": 1,
    "medianPrice": 40000000,
    "minPrice": 40000000,
    "maxPrice": 40000000,
    "medianArea": 2.1126600000000297,
    "medianPerSqft": 8247,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna Road",
        1
      ]
    ]
  },
  {
    "slug": "etr-the-nature-valley",
    "name": "etr the nature valley",
    "listings": 1,
    "medianPrice": 15366000,
    "minPrice": 15366000,
    "maxPrice": 15366000,
    "medianArea": 10638.000000001064,
    "medianPerSqft": 1444,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "the-nature-valley",
    "name": "The Nature Valley",
    "listings": 1,
    "medianPrice": 13125000,
    "minPrice": 13125000,
    "maxPrice": 13125000,
    "medianArea": 7875.000000000788,
    "medianPerSqft": 1667,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 0,
    "villages": [
      [
        "Sector 35 Gurgaon",
        1
      ]
    ]
  },
  {
    "slug": "jjss-farm-house",
    "name": "JJSS Farm House",
    "listings": 1,
    "medianPrice": 25000000,
    "minPrice": 25000000,
    "maxPrice": 25000000,
    "medianArea": 10899.00000000109,
    "medianPerSqft": 2294,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 0,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "dlf-farms-sohna",
    "name": "dlf farms sohna",
    "listings": 1,
    "medianPrice": 25000000,
    "minPrice": 25000000,
    "maxPrice": 25000000,
    "medianArea": 21780.00000000218,
    "medianPerSqft": 1148,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 0,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "dlf-spring-field-sohna",
    "name": "DLF SPRING field SOHNA",
    "listings": 1,
    "medianPrice": 45000000,
    "minPrice": 45000000,
    "maxPrice": 45000000,
    "medianArea": 4840,
    "medianPerSqft": 9297,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "West",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna Road",
        1
      ]
    ]
  },
  {
    "slug": "farm-house",
    "name": "FARM HOUSE",
    "listings": 1,
    "medianPrice": 350000000,
    "minPrice": 350000000,
    "maxPrice": 350000000,
    "medianArea": 88470.00000000885,
    "medianPerSqft": 3956,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Aklimpur",
        1
      ]
    ]
  },
  {
    "slug": "binjopur",
    "name": "binjopur",
    "listings": 1,
    "medianPrice": 37000000,
    "minPrice": 37000000,
    "maxPrice": 37000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 849,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "South",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "organic-farms-land",
    "name": "organic farms land",
    "listings": 1,
    "medianPrice": 42500000,
    "minPrice": 42500000,
    "maxPrice": 42500000,
    "medianArea": 43560.00000000436,
    "medianPerSqft": 976,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 1,
    "readyToMove": 0,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "dlf-the-camellias",
    "name": "DLF The Camellias",
    "listings": 1,
    "medianPrice": 110000000,
    "minPrice": 110000000,
    "maxPrice": 110000000,
    "medianArea": 87120.00000000121,
    "medianPerSqft": 1263,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Power of Attorney",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sector 42 Gurgaon",
        1
      ]
    ]
  },
  {
    "slug": "jaindapur",
    "name": "jaindapur",
    "listings": 1,
    "medianPrice": 20400000,
    "minPrice": 20400000,
    "maxPrice": 20400000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 1889,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "ansal-esencia-farmhouse-teherki-palwal",
    "name": "ansal esencia farmhouse teherki palwal",
    "listings": 1,
    "medianPrice": 27000000,
    "minPrice": 27000000,
    "maxPrice": 27000000,
    "medianArea": 43560,
    "medianPerSqft": 619,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "West",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "faridabad",
    "name": "faridabad",
    "listings": 1,
    "medianPrice": 46000000,
    "minPrice": 46000000,
    "maxPrice": 46000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 1056,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "South",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "sohna",
    "name": "Sohna",
    "listings": 1,
    "medianPrice": 23000000,
    "minPrice": 23000000,
    "maxPrice": 23000000,
    "medianArea": 10350.000000001035,
    "medianPerSqft": 2222,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Near Delhi Mumbai Expressway Exit",
        1
      ]
    ]
  },
  {
    "slug": "bedarwal-consortium-sixty-three-golf-drive",
    "name": "Bedarwal Consortium Sixty Three Golf Drive",
    "listings": 1,
    "medianPrice": 36000000,
    "minPrice": 36000000,
    "maxPrice": 36000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 3333,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Kadarpur",
        1
      ]
    ]
  },
  {
    "slug": "raheja-riyasat-hills",
    "name": "Raheja Riyasat Hills",
    "listings": 1,
    "medianPrice": 21000000,
    "minPrice": 21000000,
    "maxPrice": 21000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 1944,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sector 95B Gurgaon",
        1
      ]
    ]
  },
  {
    "slug": "vatika-westin-farms-sohna",
    "name": "Vatika Westin Farms Sohna",
    "listings": 1,
    "medianPrice": 99000000,
    "minPrice": 99000000,
    "maxPrice": 99000000,
    "medianArea": 43560,
    "medianPerSqft": 2272,
    "bedrooms": [
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Bilaspur",
        1
      ]
    ]
  },
  {
    "slug": "walia-bas",
    "name": "walia bas",
    "listings": 1,
    "medianPrice": 200000000,
    "minPrice": 200000000,
    "maxPrice": 200000000,
    "medianArea": 87120.00000000121,
    "medianPerSqft": 2296,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sector 58 Gurgaon",
        1
      ]
    ]
  },
  {
    "slug": "vatika-westin-farms-sohna",
    "name": "VATIKA WESTIN FARMS SOHNA",
    "listings": 1,
    "medianPrice": 65000000,
    "minPrice": 65000000,
    "maxPrice": 65000000,
    "medianArea": 1,
    "medianPerSqft": 65000000,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "westin-vatika",
    "name": "WESTIN VATIKA",
    "listings": 1,
    "medianPrice": 70000000,
    "minPrice": 70000000,
    "maxPrice": 70000000,
    "medianArea": 43560,
    "medianPerSqft": 1606,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "West",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "dlf-spring-field-farms-sohna",
    "name": "DLF SPRING FIELD FARMS SOHNA",
    "listings": 1,
    "medianPrice": 52500000,
    "minPrice": 52500000,
    "maxPrice": 52500000,
    "medianArea": 46609.20000000065,
    "medianPerSqft": 1126,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "West",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "ansal-mughal-orchards",
    "name": "Ansal Mughal Orchards",
    "listings": 1,
    "medianPrice": 37000000,
    "minPrice": 37000000,
    "maxPrice": 37000000,
    "medianArea": 43560,
    "medianPerSqft": 849,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [
      [
        "North-West",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "green-orchid-farms",
    "name": "Green Orchid Farms",
    "listings": 1,
    "medianPrice": 50000000,
    "minPrice": 50000000,
    "maxPrice": 50000000,
    "medianArea": 43560,
    "medianPerSqft": 1147,
    "bedrooms": [
      [
        "3",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 1,
    "vaastu": 1,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna Road",
        1
      ]
    ]
  },
  {
    "slug": "country-club-pachgoan",
    "name": "country club pachgoan",
    "listings": 1,
    "medianPrice": 22000000,
    "minPrice": 22000000,
    "maxPrice": 22000000,
    "medianArea": 450.00004500000455,
    "medianPerSqft": 48889,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Pachgaon",
        1
      ]
    ]
  },
  {
    "slug": "m3m-merlin",
    "name": "M3M Merlin",
    "listings": 1,
    "medianPrice": 45000000,
    "minPrice": 45000000,
    "maxPrice": 45000000,
    "medianArea": 43560,
    "medianPerSqft": 1033,
    "bedrooms": [
      [
        "5",
        1
      ]
    ],
    "facings": [
      [
        "North-East",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sector 67 Gurgaon",
        1
      ]
    ]
  },
  {
    "slug": "ansal-retreat-eria-sohna-road-badshapur-gurgaon",
    "name": "Ansal retreat Eria Sohna road Badshapur gurgaon",
    "listings": 1,
    "medianPrice": 45000000,
    "minPrice": 45000000,
    "maxPrice": 45000000,
    "medianArea": 43560.000000000604,
    "medianPerSqft": 1033,
    "bedrooms": [
      [
        "4",
        1
      ]
    ],
    "facings": [
      [
        "South-East",
        1
      ]
    ],
    "ownership": [
      [
        "Leasehold",
        1
      ]
    ],
    "gated": 1,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Badshahpur",
        1
      ]
    ]
  },
  {
    "slug": "aarif-khan",
    "name": "aarif khan",
    "listings": 1,
    "medianPrice": 190000000,
    "minPrice": 190000000,
    "maxPrice": 190000000,
    "medianArea": 174240.00000000242,
    "medianPerSqft": 1090,
    "bedrooms": [
      [
        "5",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sohna",
        1
      ]
    ]
  },
  {
    "slug": "dlf-privana-south",
    "name": "DLF Privana South",
    "listings": 1,
    "medianPrice": 39000000,
    "minPrice": 39000000,
    "maxPrice": 39000000,
    "medianArea": 10800.00000000108,
    "medianPerSqft": 3611,
    "bedrooms": [
      [
        "1",
        1
      ]
    ],
    "facings": [
      [
        "South",
        1
      ]
    ],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 1,
    "pool": 0,
    "park": 1,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sector 77 Gurgaon",
        1
      ]
    ]
  },
  {
    "slug": "power-of-attorney",
    "name": "power of attorney",
    "listings": 1,
    "medianPrice": 100000000,
    "minPrice": 100000000,
    "maxPrice": 100000000,
    "medianArea": 1001880.000000014,
    "medianPerSqft": 100,
    "bedrooms": [
      [
        "2",
        1
      ]
    ],
    "facings": [],
    "ownership": [
      [
        "Freehold",
        1
      ]
    ],
    "gated": 0,
    "corner": 0,
    "pool": 0,
    "park": 0,
    "vaastu": 0,
    "readyToMove": 1,
    "villages": [
      [
        "Sector 62 Gurgaon",
        1
      ]
    ]
  }
];
