import type { Metadata } from "next";

/**
 * Per-tenant favicons.
 *
 * A single `app/icon.png` would apply to every tenant on the shared
 * deployment, so each client's icon set is registered here and attached
 * through the tenant layout's `generateMetadata` instead. A tenant with no
 * entry simply gets the app default rather than another client's mark.
 *
 * Icons are square PNGs generated by `scripts/` from the supplied brand file;
 * the 32px is the tab icon, 180px the iOS home-screen icon, 192/512 the PWA
 * sizes Android uses.
 */
const ICON_SETS: Record<string, string> = {
  "high-properties": "/brand/high-properties-icon",
};

export function iconsFor(clientSlug: string): Metadata["icons"] {
  const base = ICON_SETS[clientSlug];
  if (!base) return undefined;
  return {
    icon: [
      { url: `${base}-32.png`, sizes: "32x32", type: "image/png" },
      { url: `${base}-192.png`, sizes: "192x192", type: "image/png" },
      { url: `${base}-512.png`, sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: `${base}-180.png`, sizes: "180x180", type: "image/png" }],
  };
}
