/**
 * Creates a working .env.local on a fresh checkout.
 *
 * Credentials are deliberately not committed — anything written into git
 * history stays there, and a signing key in a repo is a signing key for
 * everyone who ever clones it. Instead this generates the local values, which
 * is all a development machine needs:
 *
 *   pnpm setup
 *
 * Production values (the hosted database, the live AUTH_SECRET) are set on the
 * deployment, never here.
 */
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { userInfo } from "node:os";

const TARGET = ".env.local";

if (existsSync(TARGET)) {
  console.log(`${TARGET} already exists — leaving it alone.`);
  process.exit(0);
}

const user = process.env.PGUSER || userInfo().username;

const contents = `# Generated by \`pnpm setup\`. Local development values only.
# Never put production credentials in this file — it is gitignored, but the
# deployment is where live values belong.

DATABASE_URL=postgresql://${user}@localhost:5432/gigzman_client_sites

# Signing key for dashboard session cookies. Generated fresh for this machine,
# so sessions do not carry across checkouts.
AUTH_SECRET=${randomBytes(32).toString("base64")}

# "path" serves every tenant from one origin at /{vertical}/{template}/{slug}.
# A client's own domain uses "host" plus PRIMARY_TENANT_SLUG.
TENANT_MODE=path

# Gates the template-library pages and the internal deployment index. Leave
# blank to keep them closed; set a hash with:
#   node -e "console.log(require('bcryptjs').hashSync('<password>', 10))"
PLATFORM_ADMIN_EMAIL=
PLATFORM_ADMIN_PASSWORD_HASH=
`;

await writeFile(TARGET, contents);
console.log(`Wrote ${TARGET} with a freshly generated AUTH_SECRET.`);
console.log(`Database expected at postgresql://${user}@localhost:5432/gigzman_client_sites`);
